### ISSUE TITLE
[Feature request] Add keybing for toogle and un-toogle

### ISSUE THREAD

**Issue by p4535992** [coffiarts/FoundryVTT-hot-pan#6]
Can you add a keybinding to the toogle/untoggle ?
It should be easy to integrate since you have the macros ready in this module https://github.com/dev7355608/gm-vision/blob/main/script.js, you can already find the code to integrate eventually (there is also a right click on one of the menu items on the left which is not bad )

**Comment by coffiarts** [comment]
Very nice idea, thanks for bringing it up!
Never thought about it, but looking at https://github.com/dev7355608/gm-vision/blob/main/script.js#L27, it  seems to be easy to implement. I'll give it a try asap.
The only thing to consider here IMO is that key bindings should be optional (being off by default). I am believing this because there seem to be quite strong opinions about flooding foundry with mod-induced bindings and menu buttons. I had some discord discussins about that with one of my other mods (https://github.com/coffiarts/FoundryVTT-lock-the-sheets), where I am adding a control button to the left hand menu. As I understand it, it's the recommended way not to do such things without asking the user (that's why I made that menu button over there optional as well).

**Comment by coffiarts** [comment]
This is implemented with the latest release of this mod: https://github.com/coffiarts/FoundryVTT-hot-pan/releases/tag/latest
